#!/system/bin/sh

MMC=`ls -d /sys/block/mmc*`

for n in $MMC; do
	if [ -e $n/queue/rotational ]; then
		echo 0 > $n/queue/rotational
	fi
	if [ -e $i/queue/nr_requests ]; then
		echo 8192 > $n/queue/nr_requests
	fi
  if [ -e $n/queue/iosched/fifo_batch ]; then
    echo 1 > $n/queue/iosched/fifo_batch
  fi
	if [ -e $n/queue/iosched/writes_starved ]; then
		echo 1 > $n/queue/iosched/writes_starved
	fi
	if [ -e $n/queue/read_ahead_kb ]; then
		echo 256 > $n/queue/read_ahead_kb
	fi
done

