#!/system/bin/sh

MMC=`ls -d /sys/block/mmc*`

for n in $MMC; do
	if [ -e $n/queue/rotational ]; then
		echo 0 > $n/queue/rotational;
	fi
	if [ -e $i/queue/nr_requests ]; then
		echo 8192 > $n/queue/nr_requests;
	fi
  if [ -e $n/queue/iosched/fifo_batch ]; then
    echo 1 > $n/queue/iosched/fifo_batch;
  fi
	if [ -e $n/queue/iosched/writes_starved ]; then
		echo 1 > $n/queue/iosched/writes_starved;
	fi
	if [ -e $n/queue/read_ahead_kb ]; then
		echo 256 > $n/queue/read_ahead_kb;
	fi
done

if [ -e /sys/devices/virtual/bdi/default/read_ahead_kb ]; then
  echo "256" > /sys/devices/virtual/bdi/default/read_ahead_kb;
fi

if [ -e /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_freq ]; then
	echo "800000" > /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_freq;
	if [ "`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`" -eq 200000 ]; then
     echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_freq;
	else 
		echo "100000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_freq;
	fi
	echo "800000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_wakeup_freq;
	echo "85" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load;
	echo "55" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load;
	echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step;
	echo "0" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step;
fi
